### ISSUE TITLE
大螢幕跑版

### ISSUE THREAD

**Issue by yayinchang** [5fpro/apollo#11]
剛剛發現 Project 的部分在大螢幕上會跑版 OAO"
https://imgur.com/a/BMvr5

**Comment by yayinchang** [comment]
@marsz 要我幫你修掉嗎？

**Comment by marsz** [comment]
@irene84111 哭哭
我們也沒發現
再拜託你了，感謝 Q_Q

**Comment by yayinchang** [comment]
@marsz 跑版的問題我已經修正到 `develop` 了
再麻煩你重新 deploy 唷，感謝。

**Comment by marsz** [comment]
@irene84111 收到！感謝，晚點來看

**Comment by marsz** [comment]
@irene84111 可以了，已上 production
感謝你 👯 🕺
